# Generated by Django 3.2.7 on 2022-04-29 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoecommerce', '0002_user_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='RegisteredUser',
        ),
    ]
